import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
const data = JSON.parse(await readFile(new URL('../data.json', import.meta.url)));
assert.ok(data.fetchedAt && data.source?.url && data.weather);
assert.equal(typeof data.weather.temperature, 'number', 'temperature must be a number');
assert.equal(typeof data.weather.humidity, 'number', 'humidity must be a number');
assert.ok(data.weather.temperature > -5 && data.weather.temperature < 55, 'temperature must be between -5 and 55');
assert.ok(data.weather.humidity >= 0 && data.weather.humidity <= 100, 'humidity must be between 0 and 100');
assert.ok(!Number.isNaN(Date.parse(data.fetchedAt)), 'fetchedAt must be a valid date');
assert.ok(Array.isArray(data.weather.warnings), 'warnings must be an array');
console.log('Weather data check passed.');
